# Generated by Django 3.0.10 on 2020-10-29 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMAGE',
            fields=[
                ('IMG_NO', models.AutoField(primary_key=True, serialize=False)),
                ('IMG_PATH', models.CharField(max_length=200)),
                ('REG_DATE', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('USER_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('USER_NAME', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QNA',
            fields=[
                ('QNA_NO', models.AutoField(primary_key=True, serialize=False)),
                ('QNA', models.CharField(max_length=1000)),
                ('QNA_CNT', models.IntegerField()),
                ('IMG_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.IMAGE')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.USER'),
        ),
        migrations.CreateModel(
            name='ANSWER',
            fields=[
                ('ANSWER_NO', models.AutoField(primary_key=True, serialize=False)),
                ('ANSWER', models.CharField(max_length=1000)),
                ('QNA_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.QNA')),
            ],
        ),
    ]
