# Generated by Django 3.0.10 on 2020-10-29 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0002_auto_20201029_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='IMG_NO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.IMAGE'),
        ),
    ]
