# Generated by Django 3.0.10 on 2020-10-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0003_auto_20201029_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='IMG_NO',
        ),
        migrations.DeleteModel(
            name='ANSWER',
        ),
        migrations.DeleteModel(
            name='IMAGE',
        ),
        migrations.DeleteModel(
            name='QNA',
        ),
        migrations.DeleteModel(
            name='USER',
        ),
    ]
