# Generated by Django 3.0.10 on 2020-10-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0006_auto_20201030_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_image',
            old_name='DATA_WORK',
            new_name='DATE_WORK',
        ),
    ]
